<?php

/**
 * @file
 *
 * Update Dynamic DNS provides from within Drupal
 *
 */

module_load_include('inc','ddns','ddns.services');

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function ddns_help($path, $arg) {
  // Switch based on where we're at in Drupal
  switch ($path) {
    case 'admin/help#ddns':
      // https://www.drupal.org/node/161085
      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      else {
        $filepath = dirname(__FILE__) . '/README.txt';
        if (file_exists($filepath)) {
          $readme = file_get_contents($filepath);
        }
      }
      if (!isset($readme)) {
        return NULL;
      }
      if (module_exists('markdown')) {
        $filters = module_invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }

      return $output;
  }
}

function ddns_permission() {
  return array(
    'ddns admin' => array(
      'title' => t('Administer DDNS settings'),
      'description' => t('Perform configuration for DDNS setup.'),
    ),
  );
}

/**
 * Implements hook_menu().
 *
 * Generates menu items and permissions for administration.
 */
function ddns_menu() {
  // Create the menu
  $items = array();

  $items['admin/config/development/ddns'] = array(
    'title' => 'DDNS',
    'description' => 'Configuration for DDNS',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ddns_settings_form'),
    'access arguments' => array('ddns admin'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ddns.admin.inc',
  );

  return $items;
}

/**
 * Function to obtain external IP address from ipify.org service.
 */
function ddns_current_ip() {
  $ip = file_get_contents('https://api.ipify.org');
  return $ip;
}

/**
 * Function to generate an array containing all services ready to update.
 */
function ddns_generate_service_urls() {
  $services = array();
  $ip = ddns_current_ip();
  foreach(ddns_services() as $provider => $url) {
    if ('ddns_' . $provider . '_enabled' === 1) {
      $username = variable_get('ddns_' . $provider . '_username','');
      $password = variable_get('ddns_' . $provider . '_password','');
      $hostname = variable_get('ddns_' . $provider . '_hostname','');

      $url = str_replace('[USERNAME]', $username, $url);
      $url = str_replace('[PASSWORD]', $password, $url);
      $url = str_replace('[DOMAIN]', $hostname, $url);
      $url = str_replace('[IP]', $ip, $url);

      $services[] = $url;
    };
  };
  dsm($services);
}

/**
 * Implements hook_cron().
 *
 * Runs the update process for enabled DDNS services.
 */
function ddns_cron() {
  $interval = variable_get('ddns_interval', 60) * 60;
  if (time() >= variable_get('ddns_nextrun', 0)) {
    // TODO: Create code to execute curl update on urls
  };
  variable_set('ddns_nextrun', time() + $interval);
}
